spring:
  datasource:
#    url: jdbc:h2:file:./database/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
    hikari:
      maximumPoolSize: 100
      minimumIdle: 10
      idleTimeout: 60_000
      maxLifetime: 60_000
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: false
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    # OSIV
    open-in-view: false
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        generate_statistics: true
  sql:
    init:
      mode: embedded

kakao:
  auth:
    prefix: "KakaoAK"
    accessToken: "ENC(xPI7P3eB/jn9aY6272Geq+XtnJnYrZE46FkA4bhoZazn9MAC9wYWf3nMGNtmn29goGtvsSAZNv+WSL4wTFsRaKCs+HQ9IffTf9Un3qzl53c=)"
  api:
    host: "https://dapi.kakao.com"

naver:
  auth:
    clientId: "VIKgsNdpEwXVehMBzWON"
    clientSecret: "ENC(enAIUmcyGxA3sfGyMhzJZt5RSvj+fHVR0wN8DgpSv/hp7QMM3oZQ+qey23X4BsFp)"
  api:
    host: "https://openapi.naver.com"

jasypt:
  encryptor:
    bean: stringEncryptor

localstack:
  endpoint: "http://localhost:4566"
  region: "ap-northeast-2"
  sns:
    topicPrefix: "arn:aws:sns:ap-northeast-2:000000000000:"
  sqs:
    queueUrl: "http://localhost:4566/000000000000/blog-search-api"